# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'RSS Reader' do
  pod 'couchbase-lite-ios', '~> 1.3'
  pod 'Gloss', '~> 0.7.4'
end

target 'RSS ReaderTests' do

end

target 'RSS ReaderUITests' do

end

