# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'RSS Reader' do
  pod 'couchbase-lite-ios'
  pod 'Gloss'
  pod 'MGSwipeTableCell'  
end

target 'RSS ReaderTests' do

end

target 'RSS ReaderUITests' do

end

